spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:54321/postgres
    user: postgres
    password: postgres
    enabled: true
    sqlMigrationPrefix: V
    locations:
      - 'classpath:db/migration/'